/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ForceMoveApp } from "./ForceMoveApp";

export class ForceMoveAppFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ForceMoveApp {
    return new Contract(address, _abi, signerOrProvider) as ForceMoveApp;
  }
}

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "outcome",
            type: "bytes"
          },
          {
            internalType: "bytes",
            name: "appData",
            type: "bytes"
          }
        ],
        internalType: "struct ForceMoveApp.VariablePart",
        name: "a",
        type: "tuple"
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "outcome",
            type: "bytes"
          },
          {
            internalType: "bytes",
            name: "appData",
            type: "bytes"
          }
        ],
        internalType: "struct ForceMoveApp.VariablePart",
        name: "b",
        type: "tuple"
      },
      {
        internalType: "uint256",
        name: "turnNumB",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "nParticipants",
        type: "uint256"
      }
    ],
    name: "validTransition",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "pure",
    type: "function"
  }
];
