/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PRNGInterface extends Interface {
  functions: {
    rand: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class PRNG extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PRNG;
  attach(addressOrName: string): PRNG;
  deployed(): Promise<PRNG>;

  on(event: EventFilter | string, listener: Listener): PRNG;
  once(event: EventFilter | string, listener: Listener): PRNG;
  addListener(eventName: EventFilter | string, listener: Listener): PRNG;
  removeAllListeners(eventName: EventFilter | string): PRNG;
  removeListener(eventName: any, listener: Listener): PRNG;

  interface: PRNGInterface;

  functions: {
    rand(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };

  rand(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    rand(): Promise<BigNumber>;
  };
}
