/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { BigNumberish } from "ethers/utils";

import { TransactionOverrides } from ".";
import { PRNG } from "./PRNG";

export class PRNGFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _nonce: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<PRNG> {
    return super.deploy(_nonce, overrides) as Promise<PRNG>;
  }
  getDeployTransaction(
    _nonce: BigNumberish,
    overrides?: TransactionOverrides
  ): UnsignedTransaction {
    return super.getDeployTransaction(_nonce, overrides);
  }
  attach(address: string): PRNG {
    return super.attach(address) as PRNG;
  }
  connect(signer: Signer): PRNGFactory {
    return super.connect(signer) as PRNGFactory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): PRNG {
    return new Contract(address, _abi, signerOrProvider) as PRNG;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nonce",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    inputs: [],
    name: "rand",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x60806040526000805534801561001457600080fd5b506040516101643803806101648339818101604052602081101561003757600080fd5b810190808051906020019092919050505080600081905550506101058061005f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80633b3dca7614602d575b600080fd5b60336049565b6040518082815260200191505060405180910390f35b600060016000808282540192505081905550600054336001430340604051602001808481526020018373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1660601b815260140182815260200193505050506040516020818303038152906040528051906020012060001c90509056fea2646970667358221220a883fc9c1a97bb64b88e42457bec3f009f27ac1d74ddc5177c5003c70124b00c64736f6c63430006020033";
